import type { AgentResult } from "@/types/task";
import { callLlm } from "@/integrations/llmProvider";

const DEMO_OUTPUT = (topic: string) => `
[DEMO — Scout Unit Briefing]

Topic: "${topic}"

Summary:
This is a simulated research briefing generated by the Operator Loop Scout Unit (v0.2 demo).
In a production deployment, this unit would query approved knowledge sources, summarize
findings, and return a structured operator briefing.

Key Points (Demo):
• No external API calls were made in this response.
• All content below is placeholder/illustrative only.
• This unit operates in read-only, no-network demo mode for v0.2.

Demo Findings:
1. Topic identified and classified as a research request.
2. Relevant categories: General Knowledge / Information Retrieval.
3. Confidence score: N/A (demo mode — no scoring model attached).

Recommended Action: Review this briefing and approve to log, or reject to cancel.
`.trim();

const SYSTEM_PROMPT =
  "You are the Scout Unit in a controlled operator loop. Your role is to produce concise, factual research briefings. " +
  "Format your response as a structured operator briefing with: a one-paragraph summary, 3-5 key points, and a recommended action. " +
  "Keep your response under 400 words. Do not invent facts you are unsure about — say so plainly.";

export async function runResearchAgent(input: string): Promise<AgentResult> {
  const topic = input.trim() || "the requested topic";

  const llmResult = await callLlm(
    `${SYSTEM_PROMPT}\n\nResearch request: ${topic}`
  );

  if (llmResult.source === "real_api" && llmResult.output) {
    return {
      agent: "researchAgent",
      output: llmResult.output,
      isDemo: false,
      source: "real_api",
      provider: llmResult.provider,
    };
  }

  return {
    agent: "researchAgent",
    output: DEMO_OUTPUT(topic),
    isDemo: true,
    source: "demo_fallback",
    provider: "none",
  };
}
