import type { AgentResult } from "@/types/task";

export function runResearchAgent(input: string): AgentResult {
  const topic = input.trim() || "the requested topic";

  const output = `
[DEMO — Scout Unit Briefing]

Topic: "${topic}"

Summary:
This is a simulated research briefing generated by the Operator Loop Scout Unit (v0.2 demo).
In a production deployment, this unit would query approved knowledge sources, summarize
findings, and return a structured operator briefing.

Key Points (Demo):
• No external API calls were made in this response.
• All content below is placeholder/illustrative only.
• This unit operates in read-only, no-network demo mode for v0.2.

Demo Findings:
1. Topic identified and classified as a research request.
2. Relevant categories: General Knowledge / Information Retrieval.
3. Confidence score: N/A (demo mode — no scoring model attached).

Recommended Action: Review this briefing and approve to log, or reject to cancel.
`.trim();

  return {
    agent: "researchAgent",
    output,
    isDemo: true,
  };
}
